config/routes.rb
Rails.application.routes.draw do
 
  get 'home/index'
  resources :background_assets
  resources :assets

  root 'home#index'
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  serialize :filesize_metadata, Hash

  has_attached_file :attachment, {
    styles: { 
      :thumb => {geometry: '125x100>'},
      :optimized_compress_0 => {geometry: '100%', paperclip_optimizer: {jpegrecompress: {allow_lossy: true, quality: 0}}},
      :optimized_compress_1 => {geometry: '100%', paperclip_optimizer: {jpegrecompress: {allow_lossy: true, quality: 1}}},
      :optimized_compress_2 => {geometry: '100%', paperclip_optimizer: {jpegrecompress: {allow_lossy: true, quality: 2}}},
      :optimized_compress_3 => {geometry: '100%', paperclip_optimizer: {jpegrecompress: {allow_lossy: true, quality: 3}}},
      :optimized_compress_4 => {geometry: '100%', paperclip_optimizer: {jpegrecompress: {allow_lossy: true, quality: 4}}}
    }
  }
  validates_attachment_content_type :attachment, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  process_in_background :attachment
  
  
  before_save :determine_dimensions
  # after_save :determine_style_file_sizes
  
  def determine_dimensions
    if attachment?
      tempfile = attachment.queued_for_write[:original]
      unless tempfile.nil?
        geometry = Paperclip::Geometry.from_file(tempfile)
        self.attachment_width = geometry.width.to_i
        self.attachment_height = geometry.height.to_i
      end
    end
  end
  
  def determine_style_file_sizes
    filesizes = {}
    self.attachment.styles.collect{|k,v| v.name}.each do |style|
      if Rails.application.class.config.paperclip_defaults[:storage] == :s3
        logger.info(self.attachment.url(style.to_sym))
        filesize = URI(self.attachment.url(style.to_sym)).read.size
      else
        filesize = File.read([Rails.root.to_s, "public", self.attachment.url(style)].join("/")).size
      end
      filesizes[style] = filesize
    end
    self.update_column(:filesize_metadata, filesizes)
  end      
end

app/models/background_asset.rb
class BackgroundAsset < ActiveRecord::Base
  serialize :filesize_metadata, Hash

  # upload settings
  ########################
  has_attached_file :attachment, {
    styles: { 
      :thumb => {geometry: '125x100>'},
      :optimized_compress_0 => {geometry: '100%', paperclip_optimizer: {jpegrecompress: {allow_lossy: true, quality: 0}}},
      :optimized_compress_1 => {geometry: '100%', paperclip_optimizer: {jpegrecompress: {allow_lossy: true, quality: 1}}},
      :optimized_compress_2 => {geometry: '100%', paperclip_optimizer: {jpegrecompress: {allow_lossy: true, quality: 2}}},
      :optimized_compress_3 => {geometry: '100%', paperclip_optimizer: {jpegrecompress: {allow_lossy: true, quality: 3}}},
      :optimized_compress_4 => {geometry: '100%', paperclip_optimizer: {jpegrecompress: {allow_lossy: true, quality: 4}}}
    }
  }
  validates_attachment_content_type :attachment, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  ########################

  # background processing
  ########################
  process_in_background :attachment, processing_image_url: :processing_image_fallback
  def processing_image_fallback
    options = attachment.options
    options[:interpolator].interpolate(options[:url], attachment, :original)
  end
  ########################
  

  # Filesize
  ########################
  before_save :determine_dimensions
  # after_save :determine_style_file_sizes
  def determine_dimensions
    if attachment?
      tempfile = attachment.queued_for_write[:original]
      unless tempfile.nil?
        geometry = Paperclip::Geometry.from_file(tempfile)
        self.attachment_width = geometry.width.to_i
        self.attachment_height = geometry.height.to_i
      end
    end
  end
  
  def determine_style_file_sizes
    filesizes = {}
    self.attachment.styles.collect{|k,v| v.name}.each do |style|
      if Rails.application.class.config.paperclip_defaults[:storage] == :s3
        logger.info(self.attachment.url(style.to_sym))
        filesize = URI(self.attachment.url(style.to_sym)).read.size
      else
        filesize = File.read([Rails.root.to_s, "public", self.attachment.url(style)].join("/")).size
      end
      filesizes[style] = filesize
    end
    self.update_column(:filesize_metadata, filesizes)
  end
  ########################
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  before_action :set_asset, only: [:show, :edit, :update, :destroy]

  # GET /assets
  def index
    @assets = Asset.all
  end

  # GET /assets/1
  def show
  end

  # GET /assets/new
  def new
    @asset = Asset.new
  end

  # GET /assets/1/edit
  def edit
  end

  # POST /assets
  def create
    @asset = Asset.new(asset_params)

    if @asset.save
      redirect_to @asset, notice: 'Asset was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /assets/1
  def update
    if @asset.update(asset_params)
      redirect_to @asset, notice: 'Asset was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /assets/1
  def destroy
    @asset.destroy
    redirect_to assets_url, notice: 'Asset was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asset
      @asset = Asset.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def asset_params
      params[:asset].permit(:attachment)
    end
end

app/controllers/background_assets_controller.rb
class BackgroundAssetsController < ApplicationController
  before_action :set_background_asset, only: [:show, :edit, :update, :destroy]

  # GET /background_assets
  def index
    @background_assets = BackgroundAsset.all
  end

  # GET /background_assets/1
  def show
  end

  # GET /background_assets/new
  def new
    @background_asset = BackgroundAsset.new
  end

  # GET /background_assets/1/edit
  def edit
  end

  # POST /background_assets
  def create
    @background_asset = BackgroundAsset.new(background_asset_params)

    if @background_asset.save
      redirect_to @background_asset, notice: 'Background asset was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /background_assets/1
  def update
    if @background_asset.update(background_asset_params)
      redirect_to @background_asset, notice: 'Background asset was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /background_assets/1
  def destroy
    @background_asset.destroy
    redirect_to background_assets_url, notice: 'Background asset was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_background_asset
      @background_asset = BackgroundAsset.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def background_asset_params
      params[:background_asset].permit(:attachment)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/assets/_form.html.erb
<%= form_for(@asset) do |f| %>
  <% if @asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asset.errors.count, "error") %> prohibited this asset from being saved:</h2>

      <ul>
      <% @asset.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.file_field :attachment, as: :file %>
<br />
<br /><br /><br /><br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assets/edit.html.erb
<h1>Editing asset</h1>

<%= render 'form' %>

<%= link_to 'Show', @asset %> |
<%= link_to 'Back', assets_path %>

app/views/assets/index.html.erb
<h1>Listing assets</h1>

<table cellpadding="10" >
  <thead>
    <tr>
		<td></td>
		<td>Original Filename</td>
		<td>Dimensions</td>
		<td style="width: 40%">Size</td>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @assets.each do |asset| %>
      <tr>
		<td><%= image_tag asset.attachment.url(:thumb) %></td>
		<td><%=  asset.attachment_file_name %></td>
		<td><%=  asset.attachment_width %> x <%= asset.attachment_height %></td>
		<td>Original <%= Filesize.from("#{ asset.attachment_file_size} B").pretty %>
		<br />
		<% #asset.attachment.styles.collect{|k,v| v.name}.reverse.each do |style| %>
			<%# style.to_s%>: <%# Filesize.from("#{ asset.filesize_metadata[style] } B").pretty %>
			(<%# sprintf("%.1f", ((asset.filesize_metadata[style.to_sym].to_f / asset.attachment_file_size.to_f) * 100)) %>% of original, saving 
			<%# Filesize.from("#{  asset.attachment_file_size.to_i - asset.filesize_metadata[style.to_sym] } B").pretty %> saved)
			<br />
		<%# end %>
		</td>
        <td><%= link_to 'Show', asset %></td>
        <td><%= link_to 'Edit', edit_asset_path(asset) %></td>
        <td><%= link_to 'Destroy', asset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Asset', new_asset_path %>

app/views/assets/new.html.erb
<h1>New asset</h1>

<%= render 'form' %>

<%= link_to 'Back', assets_path %>

app/views/assets/show.html.erb
<%= link_to raw("&laquo; Back to all assets"),  assets_path%>

<fieldset style="position: relative">
	<legend>Asset <%=@asset.id%></legend>
	Filename: <%= @asset.attachment_file_name %><br />
	Width: <%= @asset.attachment_width %><br />
	Height: <%= @asset.attachment_height %><br />
	Original Filesize: <%# Filesize.from("#{@asset.attachment_file_size} B").pretty %><br />
	Content Type: <%= @asset.attachment_content_type %><br />
	<div style="position: absolute; top: 20px; right: 10px">
	<%= image_tag @asset.attachment.url(:thumb) %>
	</div>
</fieldset>

Original:
<br />
<%= image_tag @asset.attachment.url(:original) %>
<br />

<% [0,1,2,3,4].each do |n| %>
  Optimized with <strong>jpegrecompress: {quality <%= n %>, allow_lossy: true}, jpegoptim: { allow_lossy: true, strip: :all, max_quality: 75 } </strong>
  <br />
  <%= image_tag @asset.attachment.url("optimized_compress_#{n}".to_sym) %>
  <hr />
<% end %>

<%= link_to 'Edit', edit_asset_path(@asset) %> |
<%= link_to 'Back', assets_path %>

app/views/background_assets/_form.html.erb
<%= form_for(@background_asset) do |f| %>
  <% if @background_asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@background_asset.errors.count, "error") %> prohibited this background_asset from being saved:</h2>

      <ul>
      <% @background_asset.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.file_field :attachment, as: :file %>
<br />
<br /><br /><br /><br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/background_assets/edit.html.erb
<h1>Editing Background Asset</h1>

<%= render 'form' %>

<%= link_to 'Show', @background_asset %> |
<%= link_to 'Back', background_assets_path %>

app/views/background_assets/index.html.erb
<h1>Listing Background Assets</h1>

<table cellpadding="10" >
  <thead>
    <tr>
    <td></td>
    <td>Original Filename</td>
    <td>Dimensions</td>
    <td style="width: 40%">Size</td>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @background_assets.each do |asset| %>
      <tr>
    <td><%= image_tag asset.attachment.url(:thumb) %></td>
    <td><%=  asset.attachment_file_name %></td>
    <td><%=  asset.attachment_width %> x <%= asset.attachment_height %></td>
    <td>Original <%= Filesize.from("#{ asset.attachment_file_size} B").pretty %>
    <br />
    <% #asset.attachment.styles.collect{|k,v| v.name}.reverse.each do |style| %>
      <%# style.to_s%>: <%# Filesize.from("#{ asset.filesize_metadata[style] } B").pretty %>
      (<%# sprintf("%.1f", ((asset.filesize_metadata[style.to_sym].to_f / asset.attachment_file_size.to_f) * 100)) %>% of original, saving 
      <%# Filesize.from("#{  asset.attachment_file_size.to_i - asset.filesize_metadata[style.to_sym] } B").pretty %> saved)
      <br />
    <%# end %>
    </td>
        <td><%= link_to 'Show', asset %></td>
        <td><%= link_to 'Edit', edit_asset_path(asset) %></td>
        <td><%= link_to 'Destroy', asset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Background asset', new_background_asset_path %>

app/views/background_assets/new.html.erb
<h1>New Background Asset</h1>

<%= render 'form' %>

<%= link_to 'Back', background_assets_path %>

app/views/background_assets/show.html.erb
<%= link_to raw("&laquo; Back to all assets"),  background_assets_path %>

<fieldset style="position: relative">
  <legend>Asset <%=@background_asset.id%></legend>
  Filename: <%= @background_asset.attachment_file_name %><br />
  Width: <%= @background_asset.attachment_width %><br />
  Height: <%= @background_asset.attachment_height %><br />
  Original Filesize: <%# Filesize.from("#{@background_asset.attachment_file_size} B").pretty %><br />
  Content Type: <%= @background_asset.attachment_content_type %><br />
  <div style="position: absolute; top: 20px; right: 10px">
  <%= image_tag @background_asset.attachment.url(:thumb) %>
  </div>
</fieldset>

Original:
<br />
<%= image_tag @background_asset.attachment.url(:original) %>
<br />

<% [0,1,2,3,4].each do |n| %>
  Optimized with <strong>jpegrecompress: {quality <%= n %>, allow_lossy: true}, jpegoptim: { allow_lossy: true, strip: :all, max_quality: 75 } </strong>
  <br />
  <%= image_tag @background_asset.attachment.url("optimized_compress_#{n}".to_sym) %>
  <hr />
<% end %>

<%= link_to 'Edit', edit_background_asset_path(@background_asset) %> |
<%= link_to 'Back', background_assets_path %>

app/views/home/index.html.erb
<h1>Example app for my blog post</h1>
<h4>
<a href="http://www.jasonfleetwoodboldt.com/writing/2017/02/20/how-to-get-your-heroku-app-to-optimize-your-images/" target="_blank">  
How to get your Heroku app to optimize your images for you automagically using Paperclip, image_optim and special buildpacks
</a>
</h4>
<br/>
<h4>
<a href="https://github.com/jasonfb/image-optim-with-paperclip-on-heroku-example-app-rails41/blob/master/README.rdoc" target="_blank">READ ME</a> to set this app up locally for development purposes.
</h4>
<br/>
<hr />
<h1>
<div style="text-align:center; text-size:2em">
<a href="/assets">TAKE ME TO THE ASSETS</a>
</div>
</h1>

<hr /><br/>
DCMA <br/>
Please use the "destroy" button to destroy any content immediately. Content is removed from the Amazon S3 buckets immediately and not preserved whatsoever. Don't believe me, you can <a href="https://github.com/jasonfb/image-optim-with-paperclip-on-heroku-example-app-rails41" target="_blank">read the source code of this app</a>. 

If you still don't believe me or aren't able to click the "Destroy" button yourself, please send DCMA requests to me using any of <a href="http://www.jasonfleetwoodboldt.com">these contact methods</a>
<br/>

<hr />
Copyright (c) 2017 Jason Fleetwood-Boldt
<br/>
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
<br/>
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ImageOptimWithPaperclipOnHerokuExampleAppRails41</title>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>